# Generated by Django 2.2.19 on 2023-04-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustomized',
            name='password',
            field=models.CharField(max_length=150),
        ),
    ]
