# Generated by Django 2.2.19 on 2023-04-16 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20230415_1522'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
