# Generated by Django 2.2.19 on 2023-04-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20230419_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingreds',
            field=models.ManyToManyField(through='recipes.IngredientInRecipe', to='recipes.Ingredients', verbose_name='ingredient'),
        ),
    ]
