# Generated by Django 2.2.19 on 2023-04-19 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20230419_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingreds',
            new_name='ingredients',
        ),
    ]
