# Generated by Django 2.2.19 on 2023-04-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_auto_20230423_1112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favourites',
            options={'ordering': ('-id',), 'verbose_name': ('Избранное',), 'verbose_name_plural': 'Избранные'},
        ),
        migrations.AlterModelOptions(
            name='ingredientinrecipe',
            options={'ordering': ('id',), 'verbose_name': ('Ингредиент в рецепте',), 'verbose_name_plural': 'Ингредиенты в рецептах'},
        ),
        migrations.AlterModelOptions(
            name='ingredients',
            options={'ordering': ('name',), 'verbose_name': ('Ингредиент',), 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': (('id',),), 'verbose_name': ('Рецепт',), 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.AlterModelOptions(
            name='shoplist',
            options={'ordering': ('-id',), 'verbose_name': ('Список покупок',)},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('id',), 'verbose_name': ('Тэг',), 'verbose_name_plural': 'Тэги'},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='recipes.IngredientInRecipe', to='recipes.Ingredients', verbose_name='Ингредиент'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(related_name='recipes', to='recipes.Tag', verbose_name='tag'),
        ),
    ]
