# Generated by Django 2.2.19 on 2023-04-19 19:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20230419_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientinrecipe',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Добавьте хоть 1 ингредиент')], verbose_name='Quantity'),
        ),
    ]
