# Generated by Django 2.2.19 on 2023-04-29 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_auto_20230429_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientinrecipe',
            old_name='quantity',
            new_name='amount',
        ),
    ]
